### ISSUE TITLE
Stream and about DA

### ISSUE THREAD

**Issue by jennjunod** [Teach-Jenn-Tech/distribute-aid#1]
@jtfairbank can you update the goal of the stream and about DA please?

**Comment by jtfairbank** [comment]
@jennjunod do we want to keep calling it OSS Thursdays or look into shifting the branding a bit?

Also is it ok to add that the stream is sponsored by [CodeSee](https://www.codesee.io/)?  They appreciate it and I think it sets a good precedent of your streams being sponsored.

**Comment by jennjunod** [comment]
Oy! I'll update the graphic, I forgot that ti's called OSS Thursdays. In my head, I called it DA Thursdays. I'll update both
